"""Configuration models for the Shoptet API extractor.

Everything is validated up front with Pydantic and any failure is re-raised as a
``UserException``, so a misconfiguration shows up as a user error (exit 1) rather
than a crash (exit 2).

Shape: the **connection** (which e-shop, which credentials) lives at config level
and the **object to extract** lives at row level, one object per config row. That
matches how the Shoptet read surface is shaped — dozens of independent
collections behind one token — and lets each object keep its own load type and
date window without them fighting over one shared state file.
"""

from __future__ import annotations

from enum import StrEnum
from typing import Any

from keboola.component.exceptions import UserException
from pydantic import BaseModel, ConfigDict, Field, ValidationError, computed_field, model_validator


class AuthType(StrEnum):
    """How to authenticate against the Shoptet API.

    ``private_token`` — a private API token generated by the merchant in the
    e-shop administration (Connections → Private API). Available on Shoptet
    Premium only, but the simplest path: one string, no installation flow.

    ``addon_oauth`` — the marketplace addon flow. The addon holds a permanent
    OAuth access token per installed e-shop and exchanges it for a 30-minute API
    access token. Works on every tariff that can install addons, but requires the
    integration to be a registered Shoptet API partner.
    """

    private_token = "private_token"
    addon_oauth = "addon_oauth"


class LoadType(StrEnum):
    full_load = "full_load"
    incremental_load = "incremental_load"


class ObjectType(StrEnum):
    """The Shoptet read surface, one object per config row.

    Every value maps to a verified endpoint in the published OpenAPI description;
    the path, fetch mode, primary key and child tables for each live in the
    endpoint registry in ``component.py``.
    """

    # --- bulk collections, read through asynchronous snapshot exports
    orders = "orders"
    order_history = "order_history"
    products = "products"
    product_pricelist_prices = "product_pricelist_prices"
    customers = "customers"
    invoices = "invoices"
    proforma_invoices = "proforma_invoices"
    credit_notes = "credit_notes"
    delivery_notes = "delivery_notes"
    proof_payments = "proof_payments"
    abandoned_carts = "abandoned_carts"
    discount_coupons = "discount_coupons"
    quantity_discounts = "quantity_discounts"
    articles = "articles"

    # --- change feeds (edits and deletes since a timestamp)
    orders_changes = "orders_changes"
    products_changes = "products_changes"
    customers_changes = "customers_changes"
    invoices_changes = "invoices_changes"
    proforma_invoices_changes = "proforma_invoices_changes"
    credit_notes_changes = "credit_notes_changes"
    proof_payments_changes = "proof_payments_changes"

    # --- stock
    stocks = "stocks"
    stock_supplies = "stock_supplies"
    stock_movements = "stock_movements"

    # --- catalogue structure and reference data
    categories = "categories"
    parametric_categories = "parametric_categories"
    brands = "brands"
    suppliers = "suppliers"
    price_lists = "price_lists"
    product_availabilities = "product_availabilities"
    product_flags = "product_flags"
    product_units = "product_units"
    product_measure_units = "product_measure_units"
    product_warranties = "product_warranties"
    filtering_parameters = "filtering_parameters"
    variant_parameters = "variant_parameters"
    surcharge_parameters = "surcharge_parameters"
    recycling_fee_categories = "recycling_fee_categories"
    consumption_taxes = "consumption_taxes"

    # --- order and customer reference data
    order_statuses = "order_statuses"
    order_sources = "order_sources"
    shipping_methods = "shipping_methods"
    payment_methods = "payment_methods"
    customer_groups = "customer_groups"
    customer_regions = "customer_regions"

    # --- marketing and content
    reviews_products = "reviews_products"
    reviews_project = "reviews_project"
    volume_discounts = "volume_discounts"
    xy_discounts = "xy_discounts"
    mailing_lists = "mailing_lists"
    unsubscribed_emails = "unsubscribed_emails"
    sales_channels = "sales_channels"
    article_sections = "article_sections"
    pages = "pages"
    discussion_posts = "discussion_posts"

    # --- single-record
    eshop = "eshop"


class DateRange(BaseModel):
    """Optional window narrowing what is pulled.

    Accepts absolute ``YYYY-MM-DD`` dates or relative expressions ("30 days ago",
    "yesterday") so a configuration can express a rolling window without being
    edited. Which query parameter a date maps to depends on the object — creation
    time for documents, change time when only that is filterable — and is decided
    by the endpoint registry.
    """

    model_config = ConfigDict(extra="ignore")

    date_from: str = ""
    date_to: str = ""


class Credentials(BaseModel):
    """Connection settings on their own.

    Parsed separately from the rest so the sync actions (Test Connection, list
    stocks, list price lists) validate only what they need — an unrelated problem
    in the extraction settings can never block a credentials test.
    """

    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    auth_type: AuthType = AuthType.private_token
    private_api_token: str = Field(default="", alias="#private_api_token")
    oauth_access_token: str = Field(default="", alias="#oauth_access_token")
    # e.g. https://123456.myshoptet.com/action/ApiOAuthServer/getAccessToken —
    # shown in the partner e-shop administration under Connections → API partner.
    oauth_token_url: str = ""
    # Overrides the API host. Exists so the component can be pointed at Shoptet's
    # public documentation mock server (https://api.docs.shoptet.com/_mock/shoptet-api/openapi)
    # for development and testing, which needs no e-shop and no real credentials.
    api_base_url: str = ""

    def __init__(self, **data: Any) -> None:
        try:
            super().__init__(**data)
        except ValidationError as e:
            messages = [f"{'.'.join(str(part) for part in err['loc'])}: {err['msg']}" for err in e.errors()]
            raise UserException(f"Configuration validation error: {', '.join(messages)}") from e

    @model_validator(mode="after")
    def _validate_credentials(self) -> Credentials:
        if self.auth_type == AuthType.private_token:
            if not self.private_api_token:
                raise ValueError(
                    "A private API token is required. Generate one in the e-shop administration under "
                    "Connections → Private API (Shoptet Premium)."
                )
        elif not self.oauth_access_token or not self.oauth_token_url:
            raise ValueError(
                "The addon OAuth flow needs both the permanent OAuth access token and the e-shop's "
                "OAuth server URL (…/action/ApiOAuthServer/getAccessToken)."
            )
        return self


class Configuration(Credentials):
    """Full configuration for one config row."""

    object: ObjectType | None = None
    load_type: LoadType = LoadType.incremental_load
    date_range: DateRange = Field(default_factory=DateRange)
    # Re-pulled tail on every incremental run, so records edited moments before
    # the previous run's watermark are not missed.
    lookback_hours: int = Field(default=24, ge=0, le=24 * 90)
    # Snapshot `include` sections (e.g. orders: notes, images, shippingDetails).
    include: list[str] = Field(default_factory=list)
    # Split nested arrays (order items, product variants, …) into their own tables.
    extract_child_tables: bool = True
    # Restricts stock_supplies / stock_movements to one stock; empty means all.
    stock_id: str = ""

    @model_validator(mode="after")
    def _validate_run(self) -> Configuration:
        if self.object is None:
            raise ValueError("Select the object to extract.")
        return self

    @computed_field
    @property
    def incremental(self) -> bool:
        return self.load_type == LoadType.incremental_load
